general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: debug
  run: tiny_llama_%date_%jobid
  seed: 42
  step: null
# infini_attention:
#   segment_length: 256
#   turn_on_memory: false
model:
  ddp_bucket_cap_mb: 120
  dtype: bfloat16
  init_method:
    # std: 0.025 # original
    std: 0.03125 # 1/sqrt(1024)=0.03125
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 128
    initializer_range: 0.02
    intermediate_size: 256
    is_llama_config: true
    max_position_embeddings: 1024
    num_attention_heads: 8
    num_hidden_layers: 1
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    # tie_word_embeddings: true
    tie_word_embeddings: false # original use true
    use_cache: true
    vocab_size: 49152

optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.00015
    lr_decay_starting_step: null
    lr_decay_steps: 2860
    lr_decay_style: cosine
    lr_warmup_steps: 715 # 20% of the total steps
    lr_warmup_style: linear
    min_decay_lr: 0.00001
  torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 0
parallelism:
  # dp: 1
  # tp: 8

  dp: 1
  tp: 2
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
data_stages:
  - name: Stable Training Stage
    start_training_step: 1
    data:
      dataset:
        dataset_overwrite_cache: false
        dataset_processing_num_proc_per_process: 1
        hf_dataset_config_name: null
        hf_dataset_or_datasets: roneneldan/TinyStories
        hf_dataset_splits: train
        text_column_name: text
      num_loading_workers: 1
      seed: 42
lighteval: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: gpt2
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  # micro_batch_size: 256
  # sequence_length: 1024
  # train_steps: 1787
  micro_batch_size: 32
  sequence_length: 1024
  train_steps: 1
  val_check_interval: -1
checkpoints:
  checkpoint_interval: 5000
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false
profiler: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
