checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: null
  save_initial_state: false
data_stages:
- data:
    dataset: null
    num_loading_workers: 1
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: benchmark_llama4.csv
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: debug
  run: llama4_%date_%jobid
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    is_llama4_config: true
    model_type: llama4
    boi_token_index: 200080
    eoi_token_index: 200081
    image_token_index: 200092
    text_config:
      attention_bias: false
      attention_chunk_size: 128
      attention_dropout: 0.0
      bos_token_id: 200000
      eos_token_id: [200001, 200002, 200003, 200007, 200008]
      hidden_act: silu
      hidden_size: 64
      initializer_range: 0.02
      intermediate_size: 64 # orig: 8192
      intermediate_size_mlp: 128 # orig: 16384
      max_position_embeddings: 64
      model_type: llama4_text
      num_attention_heads: 8
      # num_hidden_layers: 48 # this is the default from llama4
      num_hidden_layers: 2
      num_key_value_heads: 8
      # TODO: use the id from llama
      # pad_token_id: 200018
      pad_token_id: null
      rms_norm_eps: 1.0e-05
      rope_scaling:
        factor: 8.0
        high_freq_factor: 4.0
        low_freq_factor: 1.0
        original_max_position_embeddings: 64
        rope_type: llama3
      rope_theta: 500000.0
      rope_interleaved: false
      tie_word_embeddings: false
      use_cache: true
      use_qk_norm: true
      no_rope_layers: []
      vocab_size: 202048
      for_llm_compressor: false
      # num_local_experts: 16 # this is the default from llama4
      num_local_experts: 4
      num_experts_per_tok: 1
      interleave_moe_layer_step: 1
      output_router_logits: false
      router_aux_loss_coef: 0.001
      router_jitter_noise: 0.0
      head_dim: 128
    vision_config:
      attention_dropout: 0.0
      hidden_act: gelu
      hidden_size: 1408
      image_size: 336
      initializer_range: 0.02
      intermediate_size: 5632
      model_type: llama4_vision_model
      multi_modal_projector_bias: false
      norm_eps: 1.0e-05
      num_attention_heads: 16
      num_channels: 3
      num_hidden_layers: 34
      patch_size: 14
      pixel_shuffle_ratio: 0.5
      projector_dropout: 0.0
      projector_input_dim: 4096
      projector_output_dim: 4096
      rope_theta: 10000
      vision_feature_layer: -1
      vision_feature_select_strategy: default
      vision_output_dim: 4096
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 13
    lr_decay_style: cosine
    lr_warmup_steps: 2
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 2
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
# profiler:
#   profiler_export_path: ./tb_logs/fix/
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: robot-test/dummy-tokenizer-wordlevel
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 3
  sequence_length: 64
  train_steps: 2000
  val_check_interval: -1
