checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: /fsx/nouamane/checkpoints
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false
data_stages:
- data: 
    # dataset:
    #   dataset_folder:
    #   - /fsx/loubna/datasets/llama_tokenized/fineweb-edu/merged
    #   dataset_max_tokens: null
    #   dataset_read_path: null
    #   dataset_weights: null
    #   pad_samples_to_global_batch_size: false
    #   return_positions: true
    #   shuffle_files: false
    #   skip_in_stream: false
    #   token_size_in_bytes: 4
    #   tokenizer_name: meta-llama/Llama-3.2-1B
    #   use_old_brrr_dataloader: false
    #   vocab_size: 128256
    num_loading_workers: 1
    seed: 6198
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: olmoe
  run: olmoe-test
  seed: 6198
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
metrics_logging: null
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.02
    # scaling_method: NONE
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: true
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 1
    eos_token_id: 0
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 2048
    initializer_range: 0.02
    intermediate_size: 2048
    is_qwen2_config: true
    max_position_embeddings: 4096
    no_rope_layer: null
    num_attention_heads: 16
    num_hidden_layers: 2
    num_key_value_heads: 16
    pad_token_id: 1
    pretraining_tp: 1
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 10000.0
    sliding_window_size: 20
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 128256
    z_loss_coefficient: 0.001
    z_loss_enabled: true
    moe_config:
      num_experts: 8
      top_k: 2
      moe_hidden_size: 2048
      moe_intermediate_size: 1024 # output_multiplier=0.5 for swiglu
      shared_expert_hidden_size: 2048
      shared_expert_intermediate_size: 1024
      router_aux_loss_coef: 0.01
      enable_shared_expert: false
      token_dispatcher_type: allgather
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 4.0e-4
    lr_decay_starting_step: null
    lr_decay_steps: 31998
    lr_decay_style: cosine
    lr_warmup_steps: 2
    lr_warmup_style: linear
    min_decay_lr: 4.0e-5
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-8
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params: []
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 2
  expert_parallel_size: 1
  expert_data_parallel_size: 2
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
  enabled_moe: true
profiler: null
s3_upload: null
# tokenizer:
#   tokenizer_max_length: null
#   tokenizer_name_or_path: meta-llama/Llama-3.2-1B
#   tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 4
  sequence_length: 4096
  train_steps: 1000
  val_check_interval: -1
