checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints/doremi/big-run-02/proxy-280m-llama_with_100k_reference
  checkpoints_path_is_shared_file_system: true
  # resume_checkpoint_path: checkpoints_test/
  save_initial_state: false

doremi:
  domain_names: Pile-CC, Github, OpenWebText2, StackExchange, Wikipedia (en), PubMed Abstracts, USPTO Backgrounds, FreeLaw, PubMed Central, Enron Emails, HackerNews, NIH ExPorter, Books3, ArXiv, DM Mathematics, OpenSubtitles, Gutenberg (PG-19), Ubuntu IRC, BookCorpus2, EuroParl, YoutubeSubtitles, PhilPapers
  # domain_weights: 0.1500, 0.1213, 0.0872, 0.0631, 0.0340, 0.0240, 0.0281, 0.0594, 0.1599, 0.0015, 0.0058, 0.0021, 0.0605, 0.1136, 0.0209, 0.0154, 0.0202, 0.0037, 0.0065, 0.0100, 0.0093, 0.0036
  ref_model_resume_checkpoint_path: checkpoints/1

data_stages:
  - name: Stable Training Stage
    start_training_step: 1
    data:
      dataset:
        dataset_overwrite_cache: false
        dataset_processing_num_proc_per_process: 1
        hf_dataset_config_name: null

        # NOTE: this one works
        # hf_dataset_or_datasets: vicgalle/alpaca-gpt4
        # hf_dataset_splits: train
        # text_column_name: instruction

        # NOTE: too big
        # hf_dataset_or_datasets: allenai/c4
        # hf_dataset_splits: train
        # text_column_name: text

        # NOTE: good for testing
        # hf_dataset_or_datasets: miam
        # hf_dataset_splits: train
        # text_column_name: Utterance

        # hf_dataset_or_datasets: wikicorpus
        # hf_dataset_splits: train
        # text_column_name: text

        # hf_dataset_or_datasets: mc4
        # hf_dataset_splits: train
        # text_column_name: text

        # hf_dataset_or_datasets: leandro/the-pile-splitted
        # hf_dataset_splits: train
        # text_column_name: text

        hf_dataset_or_datasets: /fsx/phuc/datasets/doremi/the_pile/testset

      num_loading_workers: 1
      seed: 42
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: doremi
  run: train_280m_proxy_model
  seed: 42
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 120
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 1024
    initializer_range: 0.02
    intermediate_size: 4096
    is_llama_config: true
    max_position_embeddings: 256
    num_attention_heads: 8
    num_hidden_layers: 10
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 49152
optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_steps: 8
    lr_decay_style: cosine
    lr_warmup_steps: 2
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  # dp: 16
  dp: 2
  pp: 1
  pp_engine: 1f1b
  tp: 2
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: gpt2
  tokenizer_revision: null
tokens:
  # batch_accumulation_per_replica * micro_batch_size * dp = 4 * 8 * 16 = 512
  # 240 * 1024 = 245760
  # the doremi paper do 500k tokens per batch

  # NOTE: this causes some domain losses are 0
  # batch_accumulation_per_replica: 4
  # micro_batch_size: 8

  batch_accumulation_per_replica: 1
  micro_batch_size: 32

  limit_test_batches: 0
  limit_val_batches: 0
  sequence_length: 1024
  # train_steps: 1000
  # train_steps: 1579
  # train_steps: 100_000
  train_steps: 10
  val_check_interval: -1
