checkpoints:
  checkpoint_interval: 100
  checkpoints_path: checkpoints
  checkpoints_path_is_shared_file_system: false
  # resume_checkpoint_path: checkpoints
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 1
      hf_dataset_config_name: null
      hf_dataset_or_datasets: nanotron/minipile_100_samples
      hf_dataset_splits: train
      text_column_name: text
    num_loading_workers: 1
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: false
  project: fp8_for_nanotron
  run: bfloat16_2_layers_and_seq_len_256_and_micro_batch_128_and_lr_0.01_and_minipile_overfitting_and_fp8_branch_and_layernorm_and_custom_adam_and_tp_1_and_no_weight_decay_after_fixing_init_without_zero_grad
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
  monitor_model_states: true
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    # std: 0.25 # sqrt(1/16)
    # std: 0.125 # sqrt(1/64)
    std: 0.04419417382415922 # sqrt(1/512)
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    # hidden_act: silu
    hidden_act: gelu
    hidden_size: 512
    initializer_range: 0.02
    intermediate_size: 2048
    is_llama_config: true
    max_position_embeddings: 256
    num_attention_heads: 16
    num_hidden_layers: 2
    num_key_value_heads: 16
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 49152

optimizer:
  accumulate_grad_in_fp32: false
  learning_rate_scheduler:
    learning_rate: 0.0004
    lr_decay_starting_step: null
    lr_decay_steps: 800
    lr_decay_style: cosine
    lr_warmup_steps: 200 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 0.00006

  # learning_rate_scheduler:
  #   learning_rate: 0.01
  #   lr_decay_starting_step: null
  #   lr_decay_steps: null
  #   lr_decay_style: cosine
  #   lr_warmup_steps: 0 # 10% warm up of total training steps
  #   lr_warmup_style: linear
  #   min_decay_lr: 0.00006

  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: custom_adam
    torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 0
  clip_grad: 1.0

parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE

profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 128 # 256
  sequence_length: 256
  train_steps: 1000
  val_check_interval: -1
