checkpoints:
  checkpoint_interval: 275
  # checkpoints_path: /fsx/phuc/new_workspace/experiments/8b_llama3/llama3_8b_config/checkpoints
  checkpoints_path: /fsx/phuc/new_workspace/experiments/infini_attention_8b_llama/exp20_32k_context_and_2k_segment_length_and_finetune/checkpoints
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: /fsx/phuc/new_workspace/experiments/infini_attention_8b_llama/exp20_1b_llama2_32k_ctx_length_and_2k_seglen_and_2m_bs/checkpoints
  save_initial_state: false
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: infini_attention_8b_llama
  run: exp20_32k_context_and_2k_segment_length_and_finetune
  seed: 42
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 120
  dtype: bfloat16
  init_method:
    # std: 0.025 # original
    # std: 0.03125 # 1/sqrt(1024)=0.03125
    std: 0.022097086912079608 # 1/sqrt(2048)=0.022097086912079608
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    initializer_range: 0.02

    # NOTE: 250m
    # hidden_size: 1024
    # intermediate_size: 4096
    # num_hidden_layers: 10

    hidden_size: 2048
    intermediate_size: 8192
    num_hidden_layers: 4

    is_llama_config: true
    max_position_embeddings: 2048
    num_attention_heads: 8
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    # tie_word_embeddings: true
    tie_word_embeddings: false # original use true
    use_cache: true
    vocab_size: 49152


optimizer:
  accumulate_grad_in_fp32: false
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0001 # note: 1/2 of pythia use this for a 400m model
    lr_decay_starting_step: null
    lr_decay_steps: null
    lr_decay_style: cosine
    lr_warmup_steps: 110 # 10% warm up of total training steps
    lr_warmup_style: linear
    min_decay_lr: 1.0e-06
  torch_adam_is_fused: true
  weight_decay: 0.1
  zero_stage: 0

parallelism:
  dp: 16
  tp: 4

  # dp: 1
  # tp: 2

  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
# parallelism:
#   dp: 1
#   expert_parallel_size: 1
#   pp: 1
#   pp_engine: afab
#   tp: 1
#   tp_linear_async_communication: false
#   tp_mode: ALL_REDUCE
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: lvwerra/the-tokenizer-v1
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1 # batch_accumulation_per_replica * micro_batch_size * sequence_length * dp = 2 * 4 * 32768 * 8 = 2m
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 4
  # n_segments = 20
  # 2048 * 20 = 40960
  # 8192*14
  # # 1024*100 = 102400
  # 8192 * 14 = 114688
  # 4096 * 16 = 65536
  # 2048*16 = 32768
  sequence_length: 32768
  train_steps: 550 # 34428 / 8 = 4300
  # train_steps: 100 # 34428 / 8 = 4300
  val_check_interval: -1

data_stages:
  - name: Finetune Needle
    start_training_step: 1
    data:
      dataset:
        dataset_overwrite_cache: false
        dataset_processing_num_proc_per_process: 1
        hf_dataset_config_name: null
        hf_dataset_or_datasets: nanotron/needle_32k_finetuning_dataset
        hf_dataset_splits: train
        text_column_name: prompt
      num_loading_workers: 1
      seed: 42

# lighteval:
#   batch_size: 16
#   checkpoints_path: null
#   generation: null
#   logging:
#     hub_repo_details: null
#     hub_repo_results: null
#     hub_repo_tensorboard: HuggingFaceBR4/8b_llama3_evals
#     local_output_path: /fsx/phuc/new_workspace/experiments/8b_llama3/evals_of_the_released_ckp/logs
#     push_details_to_hub: null
#     push_results_to_hub: null
#     push_results_to_tensorboard: true
#     tensorboard_metric_prefix: e
#   parallelism:
#     dp: 8
#     pp: 1
#     pp_engine: 1f1b
#     tp: 1
#     tp_linear_async_communication: false
#     tp_mode: ALL_REDUCE
#   slurm_script_dir: /fsx/phuc/new_workspace/experiments/infini_attention_8b_llama/exp6_llama3_8b_config/lighteval/slurm_scripts
#   slurm_template: /fsx/phuc/new_workspace/experiments/infini_attention_8b_llama/exp6_llama3_8b_config/run_eval.slurm.jinja
#   tasks:
#     custom_tasks:
#     dataset_loading_processes: 8
#     max_samples: 1000
#     multichoice_continuations_start_space: null
#     no_multichoice_continuations_start_space: null
#     num_fewshot_seeds: null
#     tasks: early-signal
#   wandb:
#     wandb_project: infini_attention_8b_llama
#     wandb_entity: null
#     wandb_run_name: exp6_llama3_8b_config


logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info

# s3_upload:
#   remove_after_upload: true
#   s5cmd_concurrency: 5
#   s5cmd_numworkers: 16
#   upload_s3_path: s3://phuc-experiments/infini-attention/8b-llama/exp20_1b_llama2_32k_ctx_length_and_2k_seglen_and_2m_bs/

# experiment_logger:
#   tensorboard_logger:
#     flush_secs: 30
#     tensorboard_dir: /fsx/phuc/project_data/infini_attention/tb_logs
#   wandb_logger:
#     wandb_entity: null
#     wandb_project: infini_attention_8b_llama
