name: Run FA2-related unit tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    # Only run tests if we modify the following files
    paths:
      - "src/**/*.py"
      - "examples/**/*.py"
      - "tests/**/*.py"

  pull_request:
    branches: [ '**' ]
    paths:
     - "src/**/*.py"
     - "examples/**/*.py"
     - "tests/**/*.py"

jobs:
  tests:
    runs-on: [single-gpu, nvidia-gpu, a10, ci]
    container:
      image: runpod/pytorch:2.1.1-py3.10-cuda12.1.1-devel-ubuntu22.04
      ports:
        - 80
      options: --gpus all --shm-size "8G"
    steps:
    - uses: actions/checkout@v3

    - name: Python environment
      run: |
        which python
        python --version

    - name: Check Pytorch version
      run: |
        nvidia-smi
        python -c "import torch; print('torch:', torch.__version__, torch)"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"

    - name: Install nanotron
      # NOTE: uv can't build flash-attn
      run: |
        python -m venv $GITHUB_WORKSPACE/venv
        . $GITHUB_WORKSPACE/venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv
        uv pip install packaging
        uv pip install wheel
        uv pip install torch
        pip install "flash-attn>=2.5.0" --no-build-isolation
        uv pip install -e .
        uv pip install -e .[dev]
        uv pip install -e .[test]

    - name: Show installed libraries and their versions
      run: |
        . $GITHUB_WORKSPACE/venv/bin/activate
        uv pip freeze | tee installed.txt

    - name: Run tests
      # NOTE: -m fa2 will only run the unit tests that have the mark
      # "fa2" (these are FA2-related tests)
      run: |
        . $GITHUB_WORKSPACE/venv/bin/activate
        pytest -m fa2 --color=yes --durations=0 --ignore tests/fp8 --verbose tests/
